Write a Python program to convert an array to an ordinary list with the same items.

In [1]:
import numpy as np
def my_function(array):
    list = array.tolist()
    print (list)
array = np.array([[1,2,3],[4,5,6]])
my_function(array)

[[1, 2, 3], [4, 5, 6]]


Write a NumPy program to compute the sum of the diagonal element of a given array.

In [23]:
import numpy as np
def sum_diagonal(array):
    diag = np.diagonal(array)
    print("\nSum of Diagonal elements is:")
    print(sum(diag))
array = np.array([[10,88,39],[40,59,68],[10,55,74]])
sum_diagonal(array)  


Sum of Diagonal elements is:
143


Given an array of your choice, get all the values higher than X :if a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2.

In [42]:
import numpy as np
x = np.array([[1,7],[3,5],[2,75]])
y= int(input("Entrez la valeur de y: "))
print("Values bigger than y =", x[x>y])

Entrez la valeur de y: 2
Values bigger than y = [ 7  3  5 75]


Given two arrays A&B having the same shape. The task is to apply addition of A and B : C is the new array. 

In [48]:
import numpy as np
def my_function(array1, array2):
    array3= np.array([])
    if array1.shape == array2.shape:
        array3= array1+array2
        print(array3)
array1=np.array([[1,8,3],[4,9,6],[0,5,7]])
array2=np.array([[2,1,39],[4,5,1],[1,7,4]])
my_function(array1,array2)
        

[[ 3  9 42]
 [ 8 14  7]
 [ 1 12 11]]
